name: Deploy App
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the image
        run: docker build -t vivek091195/learn-docker -f Dockerfile.dev .
      - name: Run the tests
        run: docker run -e CI=true vivek091195/learn-docker npm test